# Change these first
owner: Azael-Dev # Your GitHub organization or username, where this repository lives
repo: azael-status # The name of this repository
user-agent: Azael-Dev # The user-agent header sent with each request

sites:
  - name: Web Server
    icon: https://status.azael.dev/images/icons/server.png
    url: $UPTIME_WEB_SERVER_URL
    type: globalping
    check: tcp-ping
    port: 443
    location: South-eastern Asia
    maxResponseTime: 1500

  - name: Portal
    icon: https://status.azael.dev/images/icons/portal.png
    url: https://portal.azael.dev
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

  - name: CFX Store
    icon: https://status.azael.dev/images/icons/store.png
    url: https://cfx.azael.dev
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
      - 403

  - name: CFX BanDB
    icon: https://status.azael.dev/images/icons/ban.png
    url: https://bandb.azael.dev
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
      - 403

  - name: Documentation
    icon: https://status.azael.dev/images/icons/doc.png
    url: https://docs.azael.dev
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

  - name: Documentation (Legacy)
    icon: https://status.azael.dev/images/icons/doc.png
    url: https://docs-old.azael.dev
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

  - name: Database
    icon: https://status.azael.dev/images/icons/database.png
    url: https://api.azael.dev/$UPPTIME_DATABASE_HEALTH_ENDPOINT
    method: POST
    headers:
      - "Authorization: Bearer $UPPTIME_API_TOKEN"
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"status":"unhealthy"'

  - name: Mailer
    icon: https://status.azael.dev/images/icons/email.png
    url: https://api.azael.dev/$UPPTIME_MAILER_HEALTH_ENDPOINT
    method: POST
    headers:
      - "Authorization: Bearer $UPPTIME_API_TOKEN"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"status":"unhealthy"'

  - name: Base API
    icon: https://status.azael.dev/images/icons/api.png
    url: https://api.azael.dev/$UPPTIME_API_PING_ENDPOINT
    method: POST
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status":"ok"'

  - name: Script License API
    icon: https://status.azael.dev/images/icons/license.png
    url: https://api.azael.dev/$UPPTIME_SCRIPT_LICENSE_API_ENDPOINT
    method: POST
    headers:
      - "Authorization: Bearer $UPPTIME_API_TOKEN"
      - "Content-Type: application/json"
    body: '{"licenseKey":"$UPPTIME_SCRIPT_LICENSE_BY_EMAIL"}'
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"status":"unhealthy"'

  - name: BanDB Report API
    icon: https://status.azael.dev/images/icons/ban-report.png
    url: https://api.azael.dev/$UPPTIME_BANDB_REPORT_API_ENDPOINT
    method: POST
    headers:
      - "Authorization: Bearer $UPPTIME_API_TOKEN"
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"status":"unhealthy"'

  - name: BanDB Lookup API
    icon: https://status.azael.dev/images/icons/ban-lookup.png
    url: https://bandb.azael.dev/api/v1/identifier/$UPPTIME_BANDB_LOOKUP_IDENTIFIER
    headers:
      - "Authorization: Bearer $UPPTIME_BANDB_API_TOKEN"
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
      - 403

  - name: Bot Server
    icon: https://status.azael.dev/images/icons/server.png
    url: $UPPTIME_BOT_SERVER_IP
    check: tcp-ping
    port: 443
    maxResponseTime: 1500

  - name: Discord Bot
    icon: https://status.azael.dev/images/icons/discord.png
    url: $UPPTIME_BOT_SERVER_IP
    check: tcp-ping
    port: 8138
    maxResponseTime: 1500

  - name: Cloudflare Status
    icon: https://status.azael.dev/images/icons/cloudflare.png
    url: https://www.cloudflarestatus.com/api/v2/status.json
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"indicator":"critical"'
    __dangerous__body_degraded: '"indicator":"major"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.azael.dev
  # baseUrl: /azael-status
  favicon: https://status.azael.dev/images/logo.png
  logoUrl: https://status.azael.dev/images/logo.png
  name: Azael Status
  introTitle: "**Azael Service Status**"
  introMessage: This is the **real-time** status page. Stay updated on service health and availability.
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
    - title: Contact Us
      href: https://azael.dev/links/discord
  # Theme for status page: light, dark, night, ocean
  theme: dark
  # Custom CSS
  links:
    - rel: stylesheet
      href: https://status.azael.dev/css/custom.css
  # Custom JS
  scripts:
    - src: https://status.azael.dev/js/custom.js

i18n:
  # allSystemsOperational: All services are operational
  liveStatus: Service Status
  duration30D: "Uptime over the past 30 days."
  overallUptime: "$UPTIME"
  footer: ©<span id="footer-year"></span> [Azael Dev](https://www.azael.dev), Powered by [Upptime](https://upptime.js.org) on [GitHub](https://github.com/Azael-Dev/azael-status)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
