# Change these first
owner: Azael-Dev # Your GitHub organization or username, where this repository lives
repo: azael-status # The name of this repository
user-agent: Azael-Dev # The user-agent header sent with each request

sites:
  - name: Web Server
    url: $SITE_WEB_SERVER
    icon: https://status-test.azael.dev/images/icons/server.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Portal
    url: https://portal.azael.dev
    icon: https://status-test.azael.dev/images/icons/portal.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: CFX Store
    url: https://cfx.azael.dev
    icon: https://status-test.azael.dev/images/icons/store.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 403

  - name: CFX BanDB
    url: https://bandb.azael.dev
    icon: https://status-test.azael.dev/images/icons/ban.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 403

  - name: Documentation
    url: https://docs.azael.dev
    icon: https://status-test.azael.dev/images/icons/doc.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Documentation (Legacy)
    url: https://docs-old.azael.dev
    icon: https://status-test.azael.dev/images/icons/doc.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Database
    method: POST
    headers:
      - "Authorization: Bearer $UPPTIME_API_TOKEN"
    url: https://api-test.azael.dev/$UPPTIME_DATABASE_HEALTH_ENDPOINT
    icon: https://status-test.azael.dev/images/icons/database.png
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200

  - name: Mailer
    method: POST
    headers:
      - "Authorization: Bearer $UPPTIME_API_TOKEN"
    url: https://api-test.azael.dev/$UPPTIME_MAILER_HEALTH_ENDPOINT
    icon: https://status-test.azael.dev/images/icons/email.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Base API
    method: POST
    url: https://api-test.azael.dev/$UPPTIME_API_PING_ENDPOINT
    icon: https://status-test.azael.dev/images/icons/api.png
    maxResponseTime: 1000
    expectedStatusCodes:
      - 200

  - name: Bot Server
    url: $UPPTIME_BOT_SERVER_URL
    icon: https://status-test.azael.dev/images/icons/server.png
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200

  - name: Discord Bot
    method: POST
    url: $UPPTIME_DISCORD_BOT_URL
    icon: https://status-test.azael.dev/images/icons/discord.png
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-test.azael.dev
  # baseUrl: /azael-status
  favicon: https://status-test.azael.dev/images/logo.png
  logoUrl: https://status-test.azael.dev/images/logo.png
  name: Azael Status
  introTitle: "**Azael Service Status**"
  introMessage: This is the **real-time** status page. Stay updated on service health and availability.
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
    - title: Contact Us
      href: https://azael.dev/links/discord
  # Theme for status page: light, dark, night, ocean
  theme: dark
  # Custom CSS
  links:
    - rel: stylesheet
      href: https://status-test.azael.dev/css/custom.css
  # Custom JS
  scripts:
    - src: https://status-test.azael.dev/js/custom.js

i18n:
  duration30D: "Uptime over the past 30 days."
  overallUptime: "$UPTIME uptime"
  footer: ©<span id="footer-year"></span> [Azael Dev](https://www.azael.dev), powered by [Upptime](https://upptime.js.org) on [GitHub](https://github.com)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
