# Change these first
owner: Azael-Dev # Your GitHub organization or username, where this repository lives
repo: azael-status # The name of this repository
user-agent: Azael-Dev # The user-agent header sent with each request

sites:
  - name: Portal
    url: https://portal.azael.dev
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

  - name: Documentation
    url: https://docs.azael.dev
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

  - name: Documentation (Legacy)
    url: https://docs-old.azael.dev
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-test.azael.dev
  # baseUrl: /azael-status
  favicon: https://status-test.azael.dev/images/logo.png
  logoUrl: https://status-test.azael.dev/images/logo.png
  name: Azael Status
  introTitle: "**Azael Service Status**"
  introMessage: This is the **real-time** status page. Stay updated on service health and availability.
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
    - title: Contact Us
      href: https://azael.dev/links/discord
  # Theme for status page: light, dark, night, ocean
  theme: dark
  # Custom CSS
  links:
    - rel: stylesheet
      href: https://status-test.azael.dev/css/custom.css
  # Custom JS
  scripts:
    - src: https://status-test.azael.dev/js/custom.js

i18n:
  footer: ©<span id="footer-year"></span> [Azael Dev](https://www.azael.dev), Powered by [Upptime](https://upptime.js.org) on [GitHub](https://github.com)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
